@startuml

class Ship {
    # shipName : String
    # yearBuilt : String
    + getShipName() : String
    + setShipName(shipName : String) : void
    + getYearBuilt() : String
    + setYearBuilt(yearBuilt : String) : void
    + toString() : String
    + printShip() : void
}

class CargoShip extends Ship {
    - cargoCapacityInTonnage : int
    + getCargoCapacityInTonnage() : int
    + setCargoCapacityInTonnage(cargoCapacityInTonnage : int) : void
    + toString() : String
}

class CruiseShip extends Ship {
    - maxNumberPassengers : int
    + getMaxNumberPassengers() : int
    + setMaxNumberPassengers(maxNumberPasengers : int) : void
    + toString() : String
}

@enduml